### ISSUE TITLE
Build hardened VM image with Packer

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-rke2-image-builder#1]
This should be built via Packer, in a CI pipeline. We should be able to build for both AWS (AMI) and Nutanix.

Requirements:
- RHEL or Ubuntu Base image options
- STIG'd image
- RKE2 pre-installed with STIG configuration

We should also aim to support as much local dev as possible.

```[tasklist]
### Tasks
- [x] Create repo to hold packer builds
- [x] Consume base Ubuntu + add STIGs in packer build for AMI
- [x] Add github workflow to build out AMI using packer
- [x] Pre-install RKE2 in packer build for AMI
- [ ] https://github.com/defenseunicorns/uds-package-dubbd/issues/502
- [ ] https://github.com/defenseunicorns/uds-rke2-image-builder/issues/7
- [ ] https://github.com/defenseunicorns/uds-rke2-image-builder/issues/8
- [ ] https://github.com/defenseunicorns/uds-rke2-image-builder/issues/10
- [ ] https://github.com/defenseunicorns/uds-rke2-image-builder/issues/29
```

**Comment by mjnagel** [comment]
Noting here that FIPS is a "paid feature" for Ubuntu, so it won't be in the scope of our "prebuilt image". Approach we can take:
- This repo builds/publishes a bottom layer of stig'd ubuntu + rke2 (but no fips)
- We also provide extra packer pieces to add a subscription (with user provided token) + enable fips, intended to be run in a user's environment

This won't be quick as seamless as we might hope for but still provides automation around the image building to the extent possible with license limitations.

**Comment by mjnagel** [comment]
Followed this approach for RKE2 - https://docs.rke2.io/install/airgap#tarball-method

**Comment by mjnagel** [comment]
Tentatively moving to review. Two follow on tasks we might have to look at:
- FIPS mode on RHEL
- Licensing handling on RHEL based on user environment

**Comment by mjnagel** [comment]
Closing this out - follow on issues with be at the repo level. Initial epic effort is completed.
