### ISSUE TITLE
RKE2 Startup/Cluster Creation Process

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-rke2-image-builder#6]
To support deployments of DUBBD/UDS packages on RKE2 on-prem we should document the process required for spinning up an RKE2 cluster on VMs.

Requirements:
- Clearly documented guide on how to spin up cluster
- Configuration should have the potential to be automated in the future
- Should use the pre-build VM image from https://github.com/defenseunicorns/uds-rke2-image-builder/issues/1
- Fully airgapped
- Should test with multi-server and multi-agent to confirm process works across large installs

```[tasklist]
### Tasks
- [x] Manual process proved out to consume VM image and spin up multi-node cluster (nodes joining cluster, leader election, etc)
- [x] Documentation of RKE2 setup
- [ ] Once IaC is available for Nutanix...automate process?
```
